### ISSUE TITLE
add ARM architecture for syncthing

### ISSUE THREAD

**Issue by froqstar** [decathorpe/fedora-pkgs#10]
I'm sure many people are using a Raspberry Pi or similar ARM SBC as a syncthing node.
As ARM is officially supported by syncthing, it would be great to have ARM builds available via your copr.

Would it be much work to add?

Great copr by the way, using it on all my fedora machines :)

**Comment by decathorpe** [comment]
Unfortunately, the only architectures currently supported by COPR are x86_64, i386, and ppc64le. I **would like** to provide arm builds for syncthing - but at the moment, I just can't due to this limitation.

I am working on getting all the necessary bits into the official fedora repositories, where I can then build syncthing on the full set of fedora's supported architectures (including arm).

The ongoing progress of an official syncthing package is tracked [here](https://bugzilla.redhat.com/show_bug.cgi?id=1427634), and I hope to get this done within the next few weeks. The package Review Request is currently blocked by 3 dependencies not being available from the fedora repositories, and I am waiting for a reviewer to look at those requests.

**Comment by froqstar** [comment]
I see, looking forward to it :)
