### ISSUE TITLE
No syncthing-inotify.service?

### ISSUE THREAD

**Issue by piotr-dobrogost** [decathorpe/fedora-pkgs#6]
Thanks for providing builds with syncthing!

After installing on Fedora 25 I get
```
$ systemctl --user enable syncthing-inotify.service
Failed to enable unit: No such file or directory
```
Any advice how to fix this?

**Comment by decathorpe** [comment]
That's strange. I guess you installed both synching and syncthing-inotify packages? Maybe systemd needs a logout-login or reboot to pick up the unit changes.

**Comment by piotr-dobrogost** [comment]
Sorry, I did not install syncthing-inotify. I somehow missed it's a separate package.Btw, maybe syncthing could install syncthing-inotify as well?

**Comment by decathorpe** [comment]
I don't know if specifying a dependency is a good idea, since syncthing-inotify is not available on, for example, RHEL/EPEL/CentOS.

**Comment by piotr-dobrogost** [comment]
You can use weak dependency *Recommends* – see *Weak Dependencies* paragraph at http://rpm.org/user_doc/dependencies.html

**Comment by decathorpe** [comment]
`syncthing-inotify` requires two go libraries to build, and go libraries' `-devel` subpackages are not available on CentOS / EPEL, where you have to bundle dependencies as far as I know - which is not something I want to do / can do.

Also, I am considering to drop the `syncthing-inotify` package entirely because the `syncthing` build system is so utterly broken I can't even update it to the latest version right now.
